kube-prometheus-stack:
  enabled: true
  prometheus:
    prometheusSpec:
      retention: 15d
      serviceMonitorSelectorNilUsesHelmValues: false
  grafana:
    enabled: true
    adminPassword: changeme
    persistence:
      enabled: true

sloRules:
  enabled: true
  successRateTarget: 0.995
